version: '3'
services:
  web:
    build: cloudpebble/
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "./cloudpebble/:/code"
    links:
      - redis
      - postgres
      - s3
      - qemu
      - ycmd
    env_file:
      - ./.env
    environment:
      - DEBUG="yes"
      - RUN_WEB="yes"
      - AWS_ENABLED="yes"
      - PORT=80
      - AWS_S3_FAKE_S3=172.245.74.113:8003
      - MEDIA_URL=http://172.245.74.113:8003/builds.cloudpebble.net/
      - QEMU_URLS=http://172.245.74.113:8001/
      - YCM_URLS=http://172.245.74.113:8002/
      - PUBLIC_URL=http://172.245.74.113/
      - LIBPEBBLE_PROXY=wss://cloudpebble-ws.herokuapp.com/tool
      - PEBBLE_AUTH_URL=https://auth.rebble.io
  celery:
    build: cloudpebble/
    restart: unless-stopped
    volumes:
      - "./cloudpebble/:/code"
    links:
      - redis
      - postgres
      - s3
    env_file:
      - ./.env
    environment:
      - DEBUG="yes"
      - RUN_CELERY="yes"
      - AWS_ENABLED=yes
      - EXPORT_ROOT=http://172.245.74.113:8003/export.cloudpebble.net/
      - AWS_S3_FAKE_S3=172.245.74.113:8003
  qemu:
    build: cloudpebble-qemu-controller/
    restart: unless-stopped
    volumes:
      - "./cloudpebble-qemu-controller/:/code"
    env_file:
      - ./.env
    ports:
      - "8001:80"
  ycmd:
    build: cloudpebble-ycmd-proxy/
    restart: unless-stopped
    volumes:
      - "./cloudpebble-ycmd-proxy/:/code"
    env_file:
      - ./.env  
    ports:
      - "8002:80"
  redis:
    #image: redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - "./data/redis:/data"
  postgres:
    #image: postgres
    image: postgres:11-alpine
    restart: unless-stopped
    volumes: 
      - "./data//postgres:/var/lib/postgresql/data2:z"
  s3:
    #image: lphoward/fake-s3
    build: fakes3/
    restart: unless-stopped
    volumes:
      - "./data/fakes3/:/fakes3_root"
    env_file:
      - ./.env
    ports:
      - "8003:4569"
  memecached:
    #image: memcached:latest
    build: ./memcached/
    restart: unless-stopped
    ports:
      - "11211:11211"
