# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-11-02 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0003_auto_20191027_2024'),
        ('ide', '0003_auto_20191030_2044'),
    ]

    operations = [
    ]
